version: '2'
services:
  speisekarte:
    build: .
    container_name: speisekarte
    image: speisekarte
    restart: always
    mem_limit: 256m
    volumes:
      - ./config.json:/app/config.json
    ports:
      - "3000:3000"
