version: '2'
services:
  speisekarte:
    build: .
    container_name: speisekarte
    image: andreldm/speisekarte:latest
    restart: unless-stopped
    mem_limit: 64m
    volumes:
      - ./config.json:/app/config.json
    ports:
      - "3000:3000"
